apiVersion: v2
name: skycluster
description: SkyCluster Helm Chart
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.0.0"

dependencies:
  - name: crossplane
    version: "1.20.0"
    repository: "https://charts.crossplane.io/stable"
  - name: submariner-k8s-broker
    version: "0.20.1"
    repository: "https://submariner-io.github.io/submariner-charts/charts"
