{{ if .Values.postInstall }}
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: kubernetes-provider
spec:
  credentials:
    source: InjectedIdentity
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: skycluster-pv
  namespace: {{ .Values.namespaces.skycluster.name }}
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: skycluster-pvc
  namespace: {{ .Values.namespaces.skycluster.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
{{ end }}