providers:
  private:  
    openstack: 
      enabled: true

# Set these settings through the command line
generateTemplate:
  skyprovider: false
generateConfigMaps: false          

savi:
  locations:
    - region: scinet
      enabled: true
      ext-os-public-subnet-name: ext-net
      ext-ProjectV3-identity-v1alpha1: 1e1c724728544ec2a9058303ddc8f30b
      ext-RouterV2-networking-v1alpha1: 0033d21d-56e2-4cde-9755-de6153167017
      zones:
        - type: cloud
          enabled: true
          labels:
            provider-category: us-east
        - type: cloud
          enabled: true
          labels:
            provider-category: us-west
        - type: cloud
          enabled: false
        - type: cloud
          enabled: false
        - type: nte
          enabled: true  
          labels:
            provider-category: us-east
        - type: nte
          enabled: true  
          labels:
            provider-category: us-east
        - type: nte
          enabled: false  
          labels:
            provider-category: us-west
        - type: nte
          enabled: false  
          labels:
            provider-category: us-west
        - type: nte
          enabled: false
        - type: nte
          enabled: false  
        - type: nte
          enabled: false  
        - type: nte
          enabled: false  
        - type: edge
          enabled: true 
          labels:
            provider-category: us-east
        - type: edge
          enabled: true 
          labels:
            provider-category: us-east
        - type: edge
          enabled: true 
          labels:
            provider-category: us-west
        - type: edge
          enabled: true 
          labels:
            provider-category: us-west
        - type: edge
          enabled: false 
          labels:
            provider-category: us-west
        - type: edge
          enabled: false 
          labels:
            provider-category: us-east
        - type: edge
          enabled: false 
          labels:
            provider-category: us-east
        - type: edge
          enabled: false 
        - type: edge
          enabled: false 
        - type: edge
          enabled: false 
        - type: edge
          enabled: false 
        - type: edge
          enabled: false 
        - type: edge
          enabled: false 
        - type: edge
          enabled: false 
        - type: edge
          enabled: false 
        - type: edge
          enabled: false 
    - region: vaughan
      enabled: true
      ext-os-public-subnet-name: ext-net
      ext-ProjectV3-identity-v1alpha1: 1e1c724728544ec2a9058303ddc8f30b
      ext-RouterV2-networking-v1alpha1: 712f6f07-374e-498a-99bd-e07a7a171cba
      zones:
      - type: cloud
        enabled: true
      - type: cloud
        enabled: false
      - type: cloud
        enabled: false
      - type: cloud
        enabled: false
      - type: nte
        enabled: true
      - type: nte
        enabled: false
      - type: nte
        enabled: false
      - type: nte
        enabled: false
      - type: nte
        enabled: false
      - type: nte
        enabled: false
      - type: nte
        enabled: false
      - type: nte
        enabled: false
      - type: edge
        enabled: true
      - type: edge
        enabled: false
      - type: edge
        enabled: false
      - type: edge
        enabled: false
      - type: edge
        enabled: false
      - type: edge
        enabled: false
      - type: edge
        enabled: false
      - type: edge
        enabled: false
      - type: edge
        enabled: false
      - type: edge
        enabled: false
      - type: edge
        enabled: false
      - type: edge
        enabled: false
      - type: edge
        enabled: false
      - type: edge
        enabled: false
      - type: edge
        enabled: false
      - type: edge
        enabled: false
