providers:
  private:  
    openstack: 
      enabled: true

# Set these settings through the command line
generateTemplate:
  skyprovider: false
generateConfigMaps: false          

savi:
  locations:
    - region: scinet
      enabled: true
      ext-os-public-subnet-name: ext-net
      ext-ProjectV3-identity-v1alpha1: 1e1c724728544ec2a9058303ddc8f30b
      ext-RouterV2-networking-v1alpha1: 0033d21d-56e2-4cde-9755-de6153167017
      zones:
        # group 1
        - type: cloud
          enabled: true
          labels:
            provider-category: us-east1
        - type: cloud
          enabled: true
          labels:
            provider-category: us-east2
        - type: cloud
          enabled: true
          labels:
            provider-category: us-east3
        - type: cloud
          enabled: true
          labels:
            provider-category: us-east4
        - type: cloud
          enabled: true
          labels:
            provider-category: us-east5
        # group 2
        - type: cloud
          enabled: true
          labels:
            provider-category: us-west1
        - type: cloud
          enabled: true
          labels:
            provider-category: us-west2
        - type: cloud
          enabled: true
          labels:
            provider-category: us-west3
        - type: cloud
          enabled: true
          labels:
            provider-category: us-west4
        - type: cloud
          enabled: true
          labels:
            provider-category: us-west5
        - type: edge
          enabled: true 
          labels:
            provider-category: us-east1
        - type: edge
          enabled: true 
          labels:
            provider-category: us-east2
        - type: edge
          enabled: true 
          labels:
            provider-category: us-east3
        - type: edge
          enabled: true 
          labels:
            provider-category: us-east4
        - type: edge
          enabled: true
          labels:
            provider-category: us-east5
        - type: edge
          enabled: true
          labels:
            provider-category: us-west1
        - type: edge
          enabled: true 
          labels:
            provider-category: us-west2
        - type: edge
          enabled: true 
          labels:
            provider-category: us-west3
        - type: edge
          enabled: true 
          labels:
            provider-category: us-west4
        - type: edge
          enabled: true 
          labels:
            provider-category: us-west5
    - region: vaughan
      enabled: false
      ext-os-public-subnet-name: ext-net
      ext-ProjectV3-identity-v1alpha1: 1e1c724728544ec2a9058303ddc8f30b
      ext-RouterV2-networking-v1alpha1: 712f6f07-374e-498a-99bd-e07a7a171cba
      zones:
      - type: cloud
        enabled: true