{{ if or .Values.install .Values.test }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: script-ip-forwarding
  namespace: skycluster-system
  labels:
    skycluster.io/managed-by: skycluster
    skycluster.io/script-type: cloud-init
    skycluster.io/script-init: ip-forwarding
data:
  cloud-init: |
    #cloud-config
    write_files:
      - path: /usr/local/bin/enable-ip-forwarding.sh
        owner: root:root
        permissions: '0755'
        content: |
          #!/bin/bash
          echo "Enable IP Forwarding" >> /root/ip-forwarding.log
          sed -i 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/' /etc/sysctl.conf
          sed -i 's/#net.ipv6.conf.all.forwarding=1/net.ipv6.conf.all.forwarding=1/' /etc/sysctl.conf
          sysctl -p
    runcmd:
      - /usr/local/bin/enable-ip-forwarding.sh
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: script-node-exporter
  namespace: skycluster-system
  labels:
    skycluster.io/managed-by: skycluster
    skycluster.io/script-type: cloud-init
    skycluster.io/script-init: node-exporter
data:
  cloud-init: |
    #cloud-config
    write_files:
      - path: /etc/systemd/system/node_exporter.service
        owner: root:root
        permissions: '0644'
        content: |
          [Unit]
          Description=Node Exporter
          After=network.target

          [Service]
          ExecStart=/usr/local/bin/node_exporter

          [Install]
          WantedBy=multi-user.target
      - path: /usr/local/bin/install-node-exporter.sh
        owner: root:root
        permissions: '0755'
        content: |
          #!/bin/bash
          echo "I've been run" >> /root/node-exporter-install.log
          install_node_exporter() {
            wget -q -P /root https://github.com/prometheus/node_exporter/releases/download/v1.10.2/node_exporter-1.10.2.linux-amd64.tar.gz
            if [ $? -eq 0 ]; then
              echo "Download succeeded" >> /root/node-exporter-install.log
              tar -zxvf /root/node_exporter-1.10.2.linux-amd64.tar.gz -C /root
              mv /root/node_exporter-1.10.2.linux-amd64/node_exporter /usr/local/bin/
              rm /root/node_exporter-1.10.2.linux-amd64.tar.gz
              rm -rf /root/node_exporter-1.10.2.linux-amd64
              return $?
            else
              echo "Download failed" >> /root/node-exporter-install.log
              return 1
            fi
          }
          # Loop until the installation succeeds
          until install_node_exporter; do
            echo "Installation failed, retrying..." >> /root/node-exporter-install.log
            sleep 5 # Wait for 5 seconds before retrying
          done
          echo "Installation Completed" >> /root/node-exporter-install.log
          systemctl daemon-reload
          systemctl enable --now node_exporter
          echo "Service activated" >> /root/node-exporter-install.log
    runcmd:
      - /usr/local/bin/install-node-exporter.sh
{{ end }}