{{ if .Values.install }}
  {{ if .Values.providers.public.azure.enabled }}
    {{- range $data := .Values.providerMappings.azure.regions }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: azure.{{ $data.region }}.global
  namespace: {{ $.Values.namespaces.skycluster.name }}
  labels:
    skycluster.io/managed-by: skycluster
    skycluster.io/config-type: provider-mappings 
    skycluster.io/provider-name: azure
    skycluster.io/provider-loc-name: {{ $data.locationName | quote}}
    skycluster.io/provider-region: {{ $data.region }}
    skycluster.io/provider-continent: {{ $data.continent | quote }}
    skycluster.io/provider-region-alias: {{ $data.regionAlias }}
    skycluster.io/provider-zone: global
    skycluster.io/provider-type: global
data:
  enabled: {{ $data.enabled | quote }}
      {{- range $key, $value := $.Values.providerMappings.azure.global }}
        {{- if typeOf $value | eq "map[string]interface {}" }}
          {{- range $key2, $value2 := $value }}
  {{ printf "%s-%s" $key $key2 }}: {{ $value2 | quote}}
          {{- end }}
        {{- else }}
  {{ $key }}: {{ $value | quote }}
        {{- end }}
      {{ end }}

      {{- range $key, $value := $data }}
        {{- if typeOf $value | ne "map[string]interface {}" }}
        {{- if typeOf $value | ne "[]interface {}" }}
  {{ $key }}: {{ $value | quote }}
        {{- end }}
        {{- end }}
      {{- end }}
---
      {{- range $zone := $data.zones }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: azure.{{ $data.region }}.default.{{ $zone.type }}
  namespace: {{ $.Values.namespaces.skycluster.name }}
  labels:
    skycluster.io/managed-by: skycluster
    skycluster.io/config-type: provider-mappings 
    skycluster.io/provider-name: azure
    skycluster.io/provider-loc-name: {{ $zone.locationName | quote}}
    skycluster.io/provider-region: {{ $data.region }}
    skycluster.io/provider-continent: {{ $data.continent | quote }}
    skycluster.io/provider-region-alias: {{ $data.regionAlias }}
    skycluster.io/provider-zone: {{ $zone.name }}
    skycluster.io/provider-type: {{ $zone.type }}
data:
  default-zone: {{ $zone.defaultZone | quote }}  
  enabled: {{ $zone.enabled | quote }}
  {{ range $image_key, $img_data := $zone.images -}}
  {{ printf "image-%s" $image_key }}: {{ $image_key }}
  {{ printf "%s" $image_key }}-sku: {{ $img_data.sku }}
  {{ printf "%s" $image_key }}-offer: {{ $img_data.offer }}
  {{ printf "%s" $image_key }}-version: {{ $img_data.version }}
  {{ printf "%s" $image_key }}-publisher: {{ $img_data.publisher }}
  {{ end -}}
  {{ range $v := $zone.flavors -}}
  {{ printf "flavor-%s" $v.flavor }}: {{ $v.name | quote }}
  {{ end }}
  {{- range $k, $v := $zone.defaults -}}
  {{ printf "default-%s" $k }}: {{ $v | quote }}
  {{ end }}
  {{- range $v := $zone.storage -}}
  {{ printf "storage-%s-price" $v.name }}: {{ $v.price | quote }}
  {{ printf "storage-%s-step" $v.name }}: {{ $v.step | quote }}
  {{ end }}
  {{- range $v := $zone.egressDataTransfer -}}
  {{ printf "egressDataTransfer-%s" ($v.name | lower) }}: {{ $v.price | quote }}
  {{ end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: azure.{{ $data.region }}.{{ $zone.name }}.{{ $zone.type }}.offerings
  namespace: {{ $.Values.namespaces.skycluster.name }}
  labels:
    skycluster.io/managed-by: skycluster
    skycluster.io/config-type: provider-vservices
    skycluster.io/vservices-family: compute
    skycluster.io/provider-name: azure
    skycluster.io/provider-loc-name: {{ $zone.locationName | quote}}
    skycluster.io/provider-region: {{ $data.region }}
    skycluster.io/provider-continent: {{ $data.continent | quote }}
    skycluster.io/provider-region-alias: {{ $data.regionAlias }}
    skycluster.io/provider-zone: {{ $zone.name }}
    skycluster.io/provider-type: {{ $zone.type }}
data:
        {{- range $k, $v := $zone -}}
          {{- if eq (typeOf $v) "[]interface {}" }}
              {{- if eq $k "flavors" }}
                {{- range $v4 := $v }}
  {{ printf "skyvm_flavor_%s" $v4.flavor }}: {{ $v4.price | quote }}
                {{- end }}
              {{- else if eq $k "storage" }}
                {{- range $v4 := $v }}
  {{ printf "skyvm_storage_%s" ($v4.name) }}: {{ $v4.price | quote }}
                {{- end }}
              {{- end }}
          {{- end }}
          {{- if eq (typeOf $v) "map[string]interface {}" }}
            {{-  if eq $k "images" }}
              {{- range $k2, $v2 := $v }}
  {{ printf "skyvm_image_%s" $k2 }}: {{ "0" | quote }}
              {{- end }}
            {{- end }}
          {{- end }}
        {{- end }}
---
      {{ end -}}
    {{ end }}
  {{ end }}
{{ end }}