{{ if .Values.install }}
  {{ if .Values.providers.public.gcp.enabled }}
    {{- range $data := .Values.providerMappings.gcp.regions }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: gcp.{{ $data.region }}.global
  namespace: {{ $.Values.namespaces.skycluster.name }}
  labels:
    skycluster.io/managed-by: skycluster
    skycluster.io/config-type: provider-mappings 
    skycluster.io/provider-name: gcp
    skycluster.io/provider-loc-name: {{ $data.locationName | quote}}
    skycluster.io/provider-region: {{ $data.region }}
    skycluster.io/provider-continent: {{ $data.continent | quote }}
    skycluster.io/provider-region-alias: {{ $data.regionAlias }}
    skycluster.io/provider-zone: global
    skycluster.io/provider-type: global
data:
  enabled: {{ $data.enabled | quote }}
      {{- range $key, $value := $.Values.providerMappings.gcp.global }}
        {{- if typeOf $value | eq "map[string]interface {}" }}
          {{- range $key2, $value2 := $value }}
                {{- if eq $key "images" }}
  {{ printf "image-%s" $key2 }}: {{ $value2 | quote }}
              {{- else }}
  {{ printf "%s-%s" $key $key2 }}: {{ $value2 | quote}}
              {{- end }}
          {{- end }}
        {{- else }}
  {{ $key }}: {{ $value | quote }}
        {{- end -}}
      {{ end -}}

      {{- range $key, $value := $data }}
        {{- if ne $key "zones" }}
  {{ $key }}: {{ $value | quote }}
        {{- end }}
      {{- end }}   
---
      {{- range $zone := $data.zones }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: gcp.{{ $data.region }}.{{ $zone.name }}.{{ $zone.type }}
  namespace: {{ $.Values.namespaces.skycluster.name }}
  labels:
    skycluster.io/managed-by: skycluster
    skycluster.io/config-type: provider-mappings 
    skycluster.io/provider-name: gcp
    skycluster.io/provider-loc-name: {{ $zone.locationName | quote}}
    skycluster.io/provider-region: {{ $data.region }}
    skycluster.io/provider-continent: {{ $data.continent | quote }}
    skycluster.io/provider-region-alias: {{ $data.regionAlias }}
    skycluster.io/provider-zone: {{ $zone.name }}
    skycluster.io/provider-type: {{ $zone.type }}
data:
  enabled: {{ $zone.enabled | quote }}
        {{- range $k, $v := $zone -}}
          {{ if eq (typeOf $v) "map[string]interface {}" }}
            {{- range $k2, $v2 := $v }}
              {{- if eq $k "images" }}
  {{ printf "image-%s" $k2 }}: {{ $v2 | quote }}
              {{- else if eq $k "defaults" }}
  {{ printf "default-%s" $k2 }}: {{ $v2 | quote }}
              {{- else }}
  {{ printf "%s-%s" $k $k2 }}: {{ $v2 | quote }}
              {{- end }}
            {{- end }}
          {{- else if eq (typeOf $v) "[]interface {}" }}
              {{- if eq $k "flavors" }}
                {{- range $v4 := $v }}
  {{ printf "flavor-%s" $v4.flavor }}: {{ $v4.name | quote }}
                {{- end }}
              {{- else if eq $k "storage" }}
                {{- range $v4 := $v }}
  {{ printf "storage-%s-price" ($v4.name) }}: {{ $v4.price | quote }}
  {{ printf "storage-%s-step" ($v4.name) }}: {{ $v4.step | quote }}
                {{- end }}
              {{- else if eq $k "egressDataTransfer" }}
                {{- range $v4 := $v }}
  {{ printf "egressDataTransfer-%s" ($v4.name | lower) }}: {{ $v4.price | quote }}
                {{- end }}
              {{- end }}
          {{- else }}
  {{ $k }}: {{ $v | quote}}
          {{- end }}
        {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gcp.{{ $data.region }}.{{ $zone.name }}.{{ $zone.type }}.offerings
  namespace: {{ $.Values.namespaces.skycluster.name }}
  labels:
    skycluster.io/managed-by: skycluster
    skycluster.io/config-type: provider-vservices
    skycluster.io/vservices-family: compute
    skycluster.io/provider-name: gcp
    skycluster.io/provider-loc-name: {{ $zone.locationName | quote}}
    skycluster.io/provider-region: {{ $data.region }}
    skycluster.io/provider-continent: {{ $data.continent | quote }}
    skycluster.io/provider-region-alias: {{ $data.regionAlias }}
    skycluster.io/provider-zone: {{ $zone.name }}
    skycluster.io/provider-type: {{ $zone.type }}
data:
        {{- range $k, $v := $zone -}}
          {{- if eq (typeOf $v) "[]interface {}" }}
              {{- if eq $k "flavors" }}
                {{- range $v4 := $v }}
  {{ printf "skyvm_flavor_%s" $v4.flavor }}: {{ $v4.price | quote }}
                {{- end }}
              {{- else if eq $k "storage" }}
                {{- range $v4 := $v }}
  {{ printf "skyvm_storage_%s" ($v4.name) }}: {{ $v4.price | quote }}
                {{- end }}
              {{- end }}
          {{- end }}
        {{- end }}
        {{- range $k, $v := $.Values.providerMappings.gcp.global.images }}
  {{ printf "skyvm_image_%s" $k }}: {{ "0" | quote }}
        {{- end }}
---
      {{ end }}
---
    {{ end }}
  {{ end }}
{{ end }}    