{{ if .Values.install }}
  {{- range $key, $func := .Values.functions }}
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: {{ $func.name }}
  labels:
    skycluster.io/managed-by: skycluster
spec:
  package: xpkg.upbound.io/crossplane-contrib/{{ $func.name }}:{{ $func.version }}
---
  {{ end }}
{{ end }}
