{{ if .Values.install }}
# skycluster namespace
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.skycluster.name }}
---
# Extra configuration needed for provider-kubernetes
apiVersion: v1
kind: ServiceAccount
metadata:
  name: skycluster-sva
  namespace: {{ .Values.namespaces.crossplane.name }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: skycluster-sva
  namespace: {{ .Values.namespaces.skycluster.name }}
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-kubernetes
spec:
  serviceAccountTemplate:
    metadata:
      name: skycluster-sva
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: provider-kubernetes-cluster-admin
subjects:
  - kind: ServiceAccount
    name: skycluster-sva
    namespace: {{ .Values.namespaces.crossplane.name }}
  - kind: ServiceAccount
    name: skycluster-sva
    namespace: {{ .Values.namespaces.skycluster.name }}
  - kind: ServiceAccount
    name: skycluster-sva
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
{{ end }}