{{ if .Values.install }}
apiVersion: v1
kind: Namespace
metadata:
  name: submariner-operator
  labels:
    skycluster.io/managed-by: skycluster
---
apiVersion: v1
kind: Namespace
metadata:
  name: skycluster-system
  labels:
    skycluster.io/managed-by: skycluster
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: skycluster-sva
  namespace: skycluster-system
  labels:
    skycluster.io/managed-by: skycluster
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-kubernetes
  labels:
    skycluster.io/managed-by: skycluster
spec:
  serviceAccountTemplate:
    metadata:
      name: skycluster-sva
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-helm
  labels:
    skycluster.io/managed-by: skycluster
spec:
  serviceAccountTemplate:
    metadata:
      name: skycluster-sva
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: provider-local-cluster-admin
  labels:
    skycluster.io/managed-by: skycluster
subjects:
  - kind: ServiceAccount
    name: skycluster-sva
    namespace: default
  - kind: ServiceAccount
    name: skycluster-sva
    namespace: crossplane-system
  - kind: ServiceAccount
    name: skycluster-sva
    namespace: skycluster-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: skycluster-pv
  namespace: skycluster-system
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: skycluster-pvc
  namespace: skycluster-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: skycluster-ca-gen
  namespace: skycluster-system
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: skycluster-sva
      containers:
        - name: skycluster-ca-gen
          image: etesami/ca-gen:latest
          env:
            - name: POD_NAMESPACE
              value: "skycluster-system"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: headscale-pvc
  namespace: skycluster-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: headscale-config-pvc
  namespace: skycluster-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
{{ end }}